/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "../Drivers/GPIO_Driver.h"
#include "../Drivers/AFIO_Driver.h"
#include "../Drivers/EXTI_Driver.h"
#include "../Drivers/NVIC.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void delay(int loops)
{
	for(int i = 0; i < loops; i++);
}

void EXTI0_IRQHandler(void)
{
	if(Check_Request_Occurence(0))
	{
		Clear_Interrupt_Flag(0);
		GPIO_ToggleOut_Pin(GPIOA, 4);

	}
}

int main(void)
{

	GPIO_ClockControl(GPIOA, ENABLE);
	GPIO_ClockControl(GPIOB, ENABLE);
	AFIO_Clock_Control(ENABLE);
	AFIO_Set_EXTI_Pin(GPIOB, 0);
	Mask_Interrupt_Request(0, ENABLE);
	Select_Rising_Trigger(0, ENABLE);

	GPIO_Init(GPIOA, 4, OUTPUT_GP_PP_2MHz);
	GPIO_Init(GPIOB, 0, INPUT_PUPD);

	GPIO_WriteToOut_Pin(GPIOB, 0, DISABLE);

	uint8_t enableNext = 1;

	Enable_Interrupt(EXTI0_IRQn);
	GPIO_WriteToOut_Pin(GPIOA, 4, ENABLE);

	while(1)
	{
		uint8_t pressValue = GPIO_ReadFromIn_Pin(GPIOB, 0);

		if(pressValue == 0 && enableNext)
		{
			delay(4000);
			if(pressValue == 0)
			{
				GPIO_ToggleOut_Pin(GPIOA, 4);
				enableNext = 0;
			}
		}
		else
		{
			delay(4000);
			if(pressValue == 1)
				enableNext = 1;
		}
	}


    /* Loop forever */
	for(;;);
}
