/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "../Drivers/GPIO_Driver.h"
#include "../Drivers/AFIO_Driver.h"
#include "../Drivers/EXTI_Driver.h"
#include "../Drivers/GP_TIM_Driver.h"
#include "../Drivers/NVIC.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void delay(int loops)
{
	for(int i = 0; i < loops; i++);
}

int main(void)
{

	GPIO_ClockControl(GPIOA, ENABLE);
	GPIO_Init(GPIOA, 2, OUTPUT_AF_PP_2MHz);

	GP_TIM_Clock_Control(TIM2, ENABLE);
	GP_TIM_Control_Setting(TIM2, ENABLE, ENABLE, DISABLE);
	GP_TIM_Interrupt_Control(TIM2, GP_TIM_CAPTURE_COMPARE3, ENABLE);
	GP_TIM_Compare_Set_Mode(TIM2, 3, 6);
	GP_TIM_Enable_Control(TIM2, 3, ENABLE);

	GP_TIM_SetCount(TIM2, 0);
	GP_TIM_SetPrescaler(TIM2, 71);
	GP_TIM_SetAutoReload(TIM2, 1000);
	GP_TIM_SetCaptureCompareValue(TIM2, 3, 800);

	while(1)
	{

	}


    /* Loop forever */
	for(;;);
}
